# Generated by Django 4.0.5 on 2022-06-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol_app', '0002_rename_desensos_club_descensos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='club',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='posicion',
        ),
    ]
